version: '3.8'

volumes:
  mysql-data:

services:
  wordpress:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ${LOCAL_WORKSPACE_FOLDER}
        target: /var/www/html
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: s72_ocean
      WORDPRESS_DB_PASSWORD: hardnugs
      WORDPRESS_DB_NAME: s72_wprasta
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/wp-admin/"]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u$$MYSQL_USER", "-p$$MYSQL_PASSWORD"]
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "pass"
      MYSQL_DATABASE: s72_wprasta
      MYSQL_USER: s72_ocean
      MYSQL_PASSWORD: hardnugs

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: "pass"
    depends_on:
      - mysql
