[character]
success_symbol = "[➜](bold green) "
error_symbol = "[✗](bold red) "

[directory]
truncation_length = 8
truncate_to_repo = true

[git_branch]
symbol = "🌱 "
truncation_length = 4
truncation_symbol = ""

[php]
symbol = "🐘 "

[nodejs]
symbol = "⬢ "
